/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manuel
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ejecucion_p = new javax.swing.JTabbedPane();
        Cargar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cargar_a = new javax.swing.JTextArea();
        archivo_t = new javax.swing.JTextField();
        cargar_b = new javax.swing.JButton();
        Configuracion = new javax.swing.JPanel();
        config_p1 = new javax.swing.JTabbedPane();
        memoria_p = new javax.swing.JPanel();
        tam_mem_l = new javax.swing.JLabel();
        tam_men_t = new javax.swing.JTextField();
        cargar_ram_b = new javax.swing.JButton();
        cargar_ram_t = new javax.swing.JTextField();
        cache1_p = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        tam_cache1_t = new javax.swing.JTextField();
        tam_cache1_l = new javax.swing.JLabel();
        tip_tam_cache1_l = new javax.swing.JLabel();
        tip_tam_cache1_cb = new javax.swing.JComboBox();
        cache2_p = new javax.swing.JPanel();
        tam_cache2_l = new javax.swing.JLabel();
        tam_cache2_t = new javax.swing.JTextField();
        tip_tam_cache2_l = new javax.swing.JLabel();
        tip_tam_cache2_cb = new javax.swing.JComboBox();
        cache3_p = new javax.swing.JPanel();
        tam_cache3_l = new javax.swing.JLabel();
        tam_cache3_t = new javax.swing.JTextField();
        tip_tam_cache3_l = new javax.swing.JLabel();
        tip_tam_cache3_cb = new javax.swing.JComboBox();
        cpu_p = new javax.swing.JPanel();
        tam_pal_l = new javax.swing.JLabel();
        tam_pal_t = new javax.swing.JTextField();
        tam_reg_l = new javax.swing.JLabel();
        tam_reg_t = new javax.swing.JTextField();
        ejecucion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ejecucion_a = new javax.swing.JTextArea();
        ejecutar_b = new javax.swing.JButton();
        ciclo_b = new javax.swing.JButton();
        salvar_t = new javax.swing.JTextField();
        exportar_b = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        cargar_a.setColumns(20);
        cargar_a.setRows(5);
        cargar_a.setText("Escriba la sentencia, o carge el documento \nen la opfión de abajo");
        jScrollPane2.setViewportView(cargar_a);

        archivo_t.setText("Archivo");
        archivo_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivo_tActionPerformed(evt);
            }
        });

        cargar_b.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargar_b.setText("Cargar");

        javax.swing.GroupLayout CargarLayout = new javax.swing.GroupLayout(Cargar);
        Cargar.setLayout(CargarLayout);
        CargarLayout.setHorizontalGroup(
            CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(CargarLayout.createSequentialGroup()
                        .addComponent(archivo_t, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cargar_b, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CargarLayout.setVerticalGroup(
            CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archivo_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargar_b))
                .addContainerGap())
        );

        ejecucion_p.addTab("Cargar", Cargar);

        tam_mem_l.setText("Tamaño de Memoria");

        cargar_ram_b.setText("Cargar RAM");

        cargar_ram_t.setText("Archivo para cargar la RAM");

        javax.swing.GroupLayout memoria_pLayout = new javax.swing.GroupLayout(memoria_p);
        memoria_p.setLayout(memoria_pLayout);
        memoria_pLayout.setHorizontalGroup(
            memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoria_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tam_mem_l)
                    .addComponent(cargar_ram_b))
                .addGap(36, 36, 36)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoria_pLayout.createSequentialGroup()
                        .addComponent(tam_men_t, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(cargar_ram_t))
                .addContainerGap())
        );
        memoria_pLayout.setVerticalGroup(
            memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoria_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_mem_l)
                    .addComponent(tam_men_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargar_ram_b)
                    .addComponent(cargar_ram_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        config_p1.addTab("Memoria", memoria_p);

        jLabel1.setText("Niveles de Cache");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        tam_cache1_l.setText("Tamaño de Cache 1:");

        tip_tam_cache1_l.setText("Tamaño de Cache en: ");

        tip_tam_cache1_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "Kb", "Mb", "Número de entradas" }));

        javax.swing.GroupLayout cache1_pLayout = new javax.swing.GroupLayout(cache1_p);
        cache1_p.setLayout(cache1_pLayout);
        cache1_pLayout.setHorizontalGroup(
            cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_pLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(tam_cache1_l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(tam_cache1_t, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(cache1_pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tip_tam_cache1_l)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip_tam_cache1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cache1_pLayout.setVerticalGroup(
            cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tam_cache1_l)
                    .addComponent(tam_cache1_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip_tam_cache1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tip_tam_cache1_l))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        config_p1.addTab("Cache1", cache1_p);

        tam_cache2_l.setText("Tamaño de Cache 2: ");

        tip_tam_cache2_l.setText("Tamaño de Cache en: ");

        tip_tam_cache2_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "Kb", "Mb", "Número de entradas" }));

        javax.swing.GroupLayout cache2_pLayout = new javax.swing.GroupLayout(cache2_p);
        cache2_p.setLayout(cache2_pLayout);
        cache2_pLayout.setHorizontalGroup(
            cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cache2_pLayout.createSequentialGroup()
                        .addComponent(tam_cache2_l)
                        .addGap(18, 18, 18)
                        .addComponent(tam_cache2_t, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cache2_pLayout.createSequentialGroup()
                        .addComponent(tip_tam_cache2_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tip_tam_cache2_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        cache2_pLayout.setVerticalGroup(
            cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_cache2_l)
                    .addComponent(tam_cache2_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip_tam_cache2_l)
                    .addComponent(tip_tam_cache2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        config_p1.addTab("Cache2", cache2_p);

        tam_cache3_l.setText("Tamaño de Cache 3:");

        tip_tam_cache3_l.setText("Tamaño de Cache en: ");

        tip_tam_cache3_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "Kb", "Mb", "Número de entradas" }));

        javax.swing.GroupLayout cache3_pLayout = new javax.swing.GroupLayout(cache3_p);
        cache3_p.setLayout(cache3_pLayout);
        cache3_pLayout.setHorizontalGroup(
            cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cache3_pLayout.createSequentialGroup()
                        .addComponent(tam_cache3_l)
                        .addGap(18, 18, 18)
                        .addComponent(tam_cache3_t, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cache3_pLayout.createSequentialGroup()
                        .addComponent(tip_tam_cache3_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tip_tam_cache3_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        cache3_pLayout.setVerticalGroup(
            cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_cache3_l)
                    .addComponent(tam_cache3_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip_tam_cache3_l)
                    .addComponent(tip_tam_cache3_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        config_p1.addTab("Cache3", cache3_p);

        tam_pal_l.setText("Tamaño de palabra: ");

        tam_pal_t.setText("32");

        tam_reg_l.setText("Número de Registros:");

        tam_reg_t.setText("32");

        javax.swing.GroupLayout cpu_pLayout = new javax.swing.GroupLayout(cpu_p);
        cpu_p.setLayout(cpu_pLayout);
        cpu_pLayout.setHorizontalGroup(
            cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpu_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cpu_pLayout.createSequentialGroup()
                        .addComponent(tam_reg_l)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cpu_pLayout.createSequentialGroup()
                        .addComponent(tam_pal_l)
                        .addGap(23, 23, 23)))
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tam_pal_t)
                    .addComponent(tam_reg_t, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        cpu_pLayout.setVerticalGroup(
            cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpu_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_pal_l)
                    .addComponent(tam_pal_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_reg_l)
                    .addComponent(tam_reg_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        config_p1.addTab("CPU", cpu_p);

        javax.swing.GroupLayout ConfiguracionLayout = new javax.swing.GroupLayout(Configuracion);
        Configuracion.setLayout(ConfiguracionLayout);
        ConfiguracionLayout.setHorizontalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config_p1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        ConfiguracionLayout.setVerticalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config_p1))
        );

        ejecucion_p.addTab("Configuracion", Configuracion);

        ejecucion_a.setEditable(false);
        ejecucion_a.setColumns(20);
        ejecucion_a.setRows(5);
        ejecucion_a.setText("Aqui se montrará la ejecución y resultados");
        jScrollPane1.setViewportView(ejecucion_a);

        ejecutar_b.setText("Ejecutar");

        ciclo_b.setText("Ciclo");

        salvar_t.setText("jTextField5");

        exportar_b.setText("Exportar");

        javax.swing.GroupLayout ejecucionLayout = new javax.swing.GroupLayout(ejecucion);
        ejecucion.setLayout(ejecucionLayout);
        ejecucionLayout.setHorizontalGroup(
            ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(ejecucionLayout.createSequentialGroup()
                        .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salvar_t, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciclo_b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exportar_b, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(ejecutar_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ejecucionLayout.setVerticalGroup(
            ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciclo_b)
                    .addComponent(ejecutar_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportar_b))
                .addContainerGap())
        );

        ejecucion_p.addTab("Ejecucion", ejecucion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ejecucion_p, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ejecucion_p)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void archivo_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivo_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivo_tActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cargar;
    private javax.swing.JPanel Configuracion;
    private javax.swing.JTextField archivo_t;
    private javax.swing.JPanel cache1_p;
    private javax.swing.JPanel cache2_p;
    private javax.swing.JPanel cache3_p;
    private javax.swing.JTextArea cargar_a;
    private javax.swing.JButton cargar_b;
    private javax.swing.JButton cargar_ram_b;
    private javax.swing.JTextField cargar_ram_t;
    private javax.swing.JButton ciclo_b;
    private javax.swing.JTabbedPane config_p1;
    private javax.swing.JPanel cpu_p;
    private javax.swing.JPanel ejecucion;
    private javax.swing.JTextArea ejecucion_a;
    private javax.swing.JTabbedPane ejecucion_p;
    private javax.swing.JButton ejecutar_b;
    private javax.swing.JButton exportar_b;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel memoria_p;
    private javax.swing.JTextField salvar_t;
    private javax.swing.JLabel tam_cache1_l;
    private javax.swing.JTextField tam_cache1_t;
    private javax.swing.JLabel tam_cache2_l;
    private javax.swing.JTextField tam_cache2_t;
    private javax.swing.JLabel tam_cache3_l;
    private javax.swing.JTextField tam_cache3_t;
    private javax.swing.JLabel tam_mem_l;
    private javax.swing.JTextField tam_men_t;
    private javax.swing.JLabel tam_pal_l;
    private javax.swing.JTextField tam_pal_t;
    private javax.swing.JLabel tam_reg_l;
    private javax.swing.JTextField tam_reg_t;
    private javax.swing.JComboBox tip_tam_cache1_cb;
    private javax.swing.JLabel tip_tam_cache1_l;
    private javax.swing.JComboBox tip_tam_cache2_cb;
    private javax.swing.JLabel tip_tam_cache2_l;
    private javax.swing.JComboBox tip_tam_cache3_cb;
    private javax.swing.JLabel tip_tam_cache3_l;
    // End of variables declaration//GEN-END:variables
}
