package interfazgrafica;
import general.*;

import java.awt.Font;
import java.awt.event.ActionListener;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manuel
 */
public class Vista extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Vista() {
        initComponents();
        Config.setVista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ejecucion_p = new javax.swing.JTabbedPane();
        Configuracion = new javax.swing.JPanel();
        config_p1 = new javax.swing.JTabbedPane();
        cpu_p = new javax.swing.JPanel();
        pal_p_linea_l = new javax.swing.JLabel();
        pal_p_linea_t = new javax.swing.JTextField();
        jerarquias_separadas_l = new javax.swing.JLabel();
        log_cb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        caches_separadas_cb = new javax.swing.JComboBox();
        memoria_p = new javax.swing.JPanel();
        m_entradas_p_pagina_l = new javax.swing.JLabel();
        m_entradas_p_pagina_t = new javax.swing.JTextField();
        m_numero_entradas = new javax.swing.JLabel();
        m_tam_memp_t = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        m_tam_virt_t = new javax.swing.JTextField();
        tlb_data_chb = new javax.swing.JCheckBox();
        tlb_inst_chb = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        n_entradas_c2_l4 = new javax.swing.JLabel();
        n_entradas_tlb_data_t = new javax.swing.JTextField();
        n_vias_c2_l4 = new javax.swing.JLabel();
        n_vias_tlb_data_t = new javax.swing.JTextField();
        politica_reemplazo_c1_l1 = new javax.swing.JLabel();
        politica_reemplazo_tlb_data_cb1 = new javax.swing.JComboBox();
        cb_tipo_tlb_datos = new javax.swing.JComboBox();
        n_entradas_c2_l6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        n_entradas_c2_l7 = new javax.swing.JLabel();
        n_entradas_tlb_inst_t = new javax.swing.JTextField();
        n_vias_c2_l6 = new javax.swing.JLabel();
        n_vias_tlb_inst_t = new javax.swing.JTextField();
        politica_reemplazo_c1_l3 = new javax.swing.JLabel();
        politica_reemplazo_tlb_inst_cb = new javax.swing.JComboBox();
        cb_tipo_tlb_inst = new javax.swing.JComboBox();
        n_entradas_c2_l8 = new javax.swing.JLabel();
        cb_tam_pagina = new javax.swing.JComboBox();
        cb_tam_memp = new javax.swing.JComboBox();
        cb_tam_virt = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        caches_p = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        niv_cache_data_cb = new javax.swing.JComboBox();
        tam_linea_t = new javax.swing.JTextField();
        tam_linea_l = new javax.swing.JLabel();
        cache1_3_p = new javax.swing.JTabbedPane();
        cache1_p = new javax.swing.JPanel();
        n_entradas_c1_l = new javax.swing.JLabel();
        n_entradas_c1_t = new javax.swing.JTextField();
        n_vias_c1_l = new javax.swing.JLabel();
        n_vias_c1_t = new javax.swing.JTextField();
        politica_reemplazo_c1_l = new javax.swing.JLabel();
        politica_reemplazo_c1_cb = new javax.swing.JComboBox();
        cb_tam_cd1 = new javax.swing.JComboBox();
        n_tipo_c1_l = new javax.swing.JLabel();
        cb_tipo_cd1 = new javax.swing.JComboBox();
        cache2_p = new javax.swing.JPanel();
        n_entradas_c2_l = new javax.swing.JLabel();
        n_entradas_c2_t = new javax.swing.JTextField();
        n_vias_c2_l = new javax.swing.JLabel();
        n_vias_c2_t = new javax.swing.JTextField();
        politica_reemplazo_c2_l = new javax.swing.JLabel();
        politica_reemplazo_c2_cb = new javax.swing.JComboBox();
        cb_tam_cd2 = new javax.swing.JComboBox();
        n_tipo_c2_l = new javax.swing.JLabel();
        cb_tipo_cd2 = new javax.swing.JComboBox();
        cache3_p = new javax.swing.JPanel();
        n_entradas_c3_l = new javax.swing.JLabel();
        n_entradas_c3_t = new javax.swing.JTextField();
        n_vias_c3_l = new javax.swing.JLabel();
        n_vias_c3_t = new javax.swing.JTextField();
        politica_reemplazo_c3_l = new javax.swing.JLabel();
        politica_reemplazo_c3_cb = new javax.swing.JComboBox();
        cb_tam_cd3 = new javax.swing.JComboBox();
        n_tipo_c3_l = new javax.swing.JLabel();
        cb_tipo_cd3 = new javax.swing.JComboBox();
        cache1_i_p = new javax.swing.JPanel();
        n_entradas_c4_l = new javax.swing.JLabel();
        n_entradas_c4_t = new javax.swing.JTextField();
        n_vias_c4_l = new javax.swing.JLabel();
        n_vias_c4_t = new javax.swing.JTextField();
        politica_reemplazo_c4_l = new javax.swing.JLabel();
        politica_reemplazo_c4_cb = new javax.swing.JComboBox();
        cb_tam_cd4 = new javax.swing.JComboBox();
        n_tipo_c4_l = new javax.swing.JLabel();
        cb_tipo_cd4 = new javax.swing.JComboBox();
        cache2_i_p = new javax.swing.JPanel();
        n_entradas_c5_l = new javax.swing.JLabel();
        n_entradas_c5_t = new javax.swing.JTextField();
        n_vias_c5_l = new javax.swing.JLabel();
        n_vias_c5_t = new javax.swing.JTextField();
        politica_reemplazo_c5_l = new javax.swing.JLabel();
        politica_reemplazo_c5_cb = new javax.swing.JComboBox();
        cb_tam_cd5 = new javax.swing.JComboBox();
        n_tipo_c5_l = new javax.swing.JLabel();
        cb_tipo_cd5 = new javax.swing.JComboBox();
        cache3_i_p = new javax.swing.JPanel();
        n_entradas_c6_l = new javax.swing.JLabel();
        n_entradas_c6_t = new javax.swing.JTextField();
        n_vias_c6_l = new javax.swing.JLabel();
        n_vias_c6_t = new javax.swing.JTextField();
        politica_reemplazo_c6_l = new javax.swing.JLabel();
        politica_reemplazo_c6_cb = new javax.swing.JComboBox();
        cb_tam_cd6 = new javax.swing.JComboBox();
        n_tipo_c6_l = new javax.swing.JLabel();
        cb_tipo_cd6 = new javax.swing.JComboBox();
        niv_cache_inst_cb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb_tipo_tam_linea = new javax.swing.JComboBox();
        ejecucion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ejecucion_a = new javax.swing.JTextArea();
        ejecutar_b = new javax.swing.JButton();
        traza_carga_b = new javax.swing.JButton();
        salvar_t = new javax.swing.JTextField();
        exportar_b = new javax.swing.JButton();
        validar_t_b = new javax.swing.JButton();
        limpiar_t_b = new javax.swing.JButton();
        ejecucion1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ejecucion_a1 = new javax.swing.JTextArea();
        ejecutar_b1 = new javax.swing.JButton();
        ciclo_b1 = new javax.swing.JButton();
        salvar_e = new javax.swing.JTextField();
        exportar_b1 = new javax.swing.JButton();
        cargar_codigo_b = new javax.swing.JButton();
        validar_c_b = new javax.swing.JButton();
        cache_d1_b = new javax.swing.JButton();
        cache_d2_b = new javax.swing.JButton();
        cache_d3_b = new javax.swing.JButton();
        cache_i1_b = new javax.swing.JButton();
        cache_i2_b = new javax.swing.JButton();
        cache_i3_b = new javax.swing.JButton();
        memoria_b = new javax.swing.JButton();
        limpiar_ej_b = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        pal_p_linea_l.setText("Bytes por palabra:");

        pal_p_linea_t.setText("4");
        pal_p_linea_t.setToolTipText("Tamaño de palabra (en bytes)");

        jerarquias_separadas_l.setText("Caché compartida desde:");

        log_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nada", "Mínimo", "Normal", "Debug" }));
        log_cb.setSelectedIndex(2);
        log_cb.setToolTipText("Nivel de detalle que aparecerá en el log de ejecución.");

        jLabel4.setText("Log");

        caches_separadas_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nivel 1", "Nivel 2", "Nivel 3", "Ninguno" }));
        caches_separadas_cb.setToolTipText("Indica desde qué nivel las cachés de datos e instrucciones serán compartidas.");

        javax.swing.GroupLayout cpu_pLayout = new javax.swing.GroupLayout(cpu_p);
        cpu_p.setLayout(cpu_pLayout);
        cpu_pLayout.setHorizontalGroup(
            cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpu_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jerarquias_separadas_l)
                    .addComponent(pal_p_linea_l))
                .addGap(18, 18, 18)
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pal_p_linea_t, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(caches_separadas_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(log_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        cpu_pLayout.setVerticalGroup(
            cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpu_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pal_p_linea_l)
                    .addComponent(pal_p_linea_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(log_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(cpu_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jerarquias_separadas_l)
                    .addComponent(caches_separadas_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        config_p1.addTab("General", cpu_p);

        m_entradas_p_pagina_l.setText("Tamaño de página:");

        m_entradas_p_pagina_t.setText("4");
        m_entradas_p_pagina_t.setToolTipText("Tamaño de página.");

        m_numero_entradas.setText("Tamaño memoria principal:");

        m_tam_memp_t.setText("32");
        m_tam_memp_t.setToolTipText("Tamaño de la memoria principal.");

        jLabel2.setText("Tamaño memoria virtual:");

        m_tam_virt_t.setText("256");
        m_tam_virt_t.setToolTipText("Tamaño de la memoria virtual.");

        tlb_data_chb.setText("TLB Data");
        tlb_data_chb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlb_data_chbActionPerformed(evt);
            }
        });

        tlb_inst_chb.setText("TLB Inst");

        n_entradas_c2_l4.setText("Número de entradas");

        n_vias_c2_l4.setText("Número de vías");

        politica_reemplazo_c1_l1.setText("Política de reemplazo");

        politica_reemplazo_tlb_data_cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));

        cb_tipo_tlb_datos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_tlb_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_tlb_datosActionPerformed(evt);
            }
        });

        n_entradas_c2_l6.setText("Tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_entradas_c2_l6)
                            .addComponent(n_entradas_c2_l4))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(politica_reemplazo_c1_l1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(politica_reemplazo_tlb_data_cb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_tipo_tlb_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(n_entradas_tlb_data_t))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(n_vias_c2_l4)
                .addGap(18, 18, 18)
                .addComponent(n_vias_tlb_data_t, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c2_l4)
                    .addComponent(n_entradas_tlb_data_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c2_l6)
                    .addComponent(cb_tipo_tlb_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_vias_c2_l4)
                    .addComponent(n_vias_tlb_data_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_tlb_data_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(politica_reemplazo_c1_l1))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TLB Data", jPanel1);

        n_entradas_c2_l7.setText("Número de entradas");

        n_entradas_tlb_inst_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_tlb_inst_tActionPerformed(evt);
            }
        });

        n_vias_c2_l6.setText("Número de vías");

        politica_reemplazo_c1_l3.setText("Política de reemplazo");

        politica_reemplazo_tlb_inst_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));

        cb_tipo_tlb_inst.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_tlb_inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_tlb_instActionPerformed(evt);
            }
        });

        n_entradas_c2_l8.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(n_entradas_c2_l8)
                            .addComponent(n_entradas_c2_l7))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(politica_reemplazo_c1_l3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(politica_reemplazo_tlb_inst_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_tipo_tlb_inst, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(n_entradas_tlb_inst_t))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(n_vias_c2_l6)
                .addGap(18, 18, 18)
                .addComponent(n_vias_tlb_inst_t, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c2_l7)
                    .addComponent(n_entradas_tlb_inst_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c2_l8)
                    .addComponent(cb_tipo_tlb_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_vias_c2_l6)
                    .addComponent(n_vias_tlb_inst_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_tlb_inst_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(politica_reemplazo_c1_l3))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TLB Inst", jPanel2);

        cb_tam_pagina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_pagina.setSelectedIndex(1);
        cb_tam_pagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_paginaActionPerformed(evt);
            }
        });

        cb_tam_memp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_memp.setSelectedIndex(2);
        cb_tam_memp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_mempActionPerformed(evt);
            }
        });

        cb_tam_virt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_virt.setSelectedIndex(2);
        cb_tam_virt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_virtActionPerformed(evt);
            }
        });

        jLabel5.setText("Configuración de TLB:");

        javax.swing.GroupLayout memoria_pLayout = new javax.swing.GroupLayout(memoria_p);
        memoria_p.setLayout(memoria_pLayout);
        memoria_pLayout.setHorizontalGroup(
            memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoria_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_entradas_p_pagina_l)
                    .addComponent(m_numero_entradas)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(m_entradas_p_pagina_t, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m_tam_memp_t, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(memoria_pLayout.createSequentialGroup()
                            .addComponent(tlb_data_chb)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tlb_inst_chb))
                        .addComponent(m_tam_virt_t, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tam_virt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_memp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        memoria_pLayout.setVerticalGroup(
            memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoria_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_entradas_p_pagina_l)
                    .addComponent(m_entradas_p_pagina_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_numero_entradas)
                    .addComponent(m_tam_memp_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_memp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(m_tam_virt_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_virt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlb_inst_chb)
                    .addGroup(memoria_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tlb_data_chb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("TLB");

        config_p1.addTab("Memoria", memoria_p);

        jLabel1.setText("Niveles de Cache Data:");

        niv_cache_data_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        niv_cache_data_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niv_cache_data_cbActionPerformed(evt);
            }
        });

        tam_linea_t.setToolTipText("Tamaño de cada bloque.");

        tam_linea_l.setText("Tamaño de línea:");

        n_entradas_c1_l.setText("Tamaño:");

        n_entradas_c1_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c1_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c1_t.setName(""); // NOI18N
        n_entradas_c1_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c1_tActionPerformed(evt);
            }
        });

        n_vias_c1_l.setText("Número de vías:");

        n_vias_c1_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c1_l.setText("Política de reemplazo:");

        politica_reemplazo_c1_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c1_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd1ActionPerformed(evt);
            }
        });

        n_tipo_c1_l.setText("Tipo:");

        cb_tipo_cd1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd1.setToolTipText("Tipo de caché.");
        cb_tipo_cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache1_pLayout = new javax.swing.GroupLayout(cache1_p);
        cache1_p.setLayout(cache1_pLayout);
        cache1_pLayout.setHorizontalGroup(
            cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c1_l)
                    .addComponent(n_entradas_c1_l)
                    .addComponent(n_tipo_c1_l))
                .addGap(24, 24, 24)
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c1_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c1_cb, 0, 150, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache1_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c1_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c1_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache1_pLayout.setVerticalGroup(
            cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c1_l)
                    .addComponent(n_entradas_c1_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c1_l)
                    .addComponent(n_vias_c1_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c1_l)
                    .addComponent(cb_tipo_cd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache1_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c1_l)
                    .addComponent(politica_reemplazo_c1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 1 Data", cache1_p);

        n_entradas_c2_l.setText("Tamaño:");

        n_entradas_c2_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c2_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c2_t.setName(""); // NOI18N
        n_entradas_c2_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c2_tActionPerformed(evt);
            }
        });

        n_vias_c2_l.setText("Número de vías:");

        n_vias_c2_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c2_l.setText("Política de reemplazo:");

        politica_reemplazo_c2_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c2_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd2ActionPerformed(evt);
            }
        });

        n_tipo_c2_l.setText("Tipo:");

        cb_tipo_cd2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd2.setToolTipText("Tipo de caché.");
        cb_tipo_cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache2_pLayout = new javax.swing.GroupLayout(cache2_p);
        cache2_p.setLayout(cache2_pLayout);
        cache2_pLayout.setHorizontalGroup(
            cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c2_l)
                    .addComponent(n_entradas_c2_l)
                    .addComponent(n_tipo_c2_l))
                .addGap(24, 24, 24)
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c2_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache2_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c2_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c2_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache2_pLayout.setVerticalGroup(
            cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c2_l)
                    .addComponent(n_entradas_c2_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c2_l)
                    .addComponent(n_vias_c2_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c2_l)
                    .addComponent(cb_tipo_cd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache2_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c2_l)
                    .addComponent(politica_reemplazo_c2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 2 Data", cache2_p);

        n_entradas_c3_l.setText("Tamaño:");

        n_entradas_c3_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c3_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c3_t.setName(""); // NOI18N
        n_entradas_c3_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c3_tActionPerformed(evt);
            }
        });

        n_vias_c3_l.setText("Número de vías:");

        n_vias_c3_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c3_l.setText("Política de reemplazo:");

        politica_reemplazo_c3_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c3_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd3ActionPerformed(evt);
            }
        });

        n_tipo_c3_l.setText("Tipo:");

        cb_tipo_cd3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd3.setToolTipText("Tipo de caché.");
        cb_tipo_cd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache3_pLayout = new javax.swing.GroupLayout(cache3_p);
        cache3_p.setLayout(cache3_pLayout);
        cache3_pLayout.setHorizontalGroup(
            cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c3_l)
                    .addComponent(n_entradas_c3_l)
                    .addComponent(n_tipo_c3_l))
                .addGap(24, 24, 24)
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c3_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c3_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache3_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c3_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c3_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache3_pLayout.setVerticalGroup(
            cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c3_l)
                    .addComponent(n_entradas_c3_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c3_l)
                    .addComponent(n_vias_c3_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c3_l)
                    .addComponent(cb_tipo_cd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache3_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c3_l)
                    .addComponent(politica_reemplazo_c3_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 3 Data", cache3_p);

        n_entradas_c4_l.setText("Tamaño:");

        n_entradas_c4_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c4_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c4_t.setName(""); // NOI18N
        n_entradas_c4_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c4_tActionPerformed(evt);
            }
        });

        n_vias_c4_l.setText("Número de vías:");

        n_vias_c4_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c4_l.setText("Política de reemplazo:");

        politica_reemplazo_c4_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c4_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd4ActionPerformed(evt);
            }
        });

        n_tipo_c4_l.setText("Tipo:");

        cb_tipo_cd4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd4.setToolTipText("Tipo de caché.");
        cb_tipo_cd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache1_i_pLayout = new javax.swing.GroupLayout(cache1_i_p);
        cache1_i_p.setLayout(cache1_i_pLayout);
        cache1_i_pLayout.setHorizontalGroup(
            cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c4_l)
                    .addComponent(n_entradas_c4_l)
                    .addComponent(n_tipo_c4_l))
                .addGap(24, 24, 24)
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c4_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c4_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache1_i_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c4_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c4_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache1_i_pLayout.setVerticalGroup(
            cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache1_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c4_l)
                    .addComponent(n_entradas_c4_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c4_l)
                    .addComponent(n_vias_c4_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c4_l)
                    .addComponent(cb_tipo_cd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache1_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c4_l)
                    .addComponent(politica_reemplazo_c4_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 1 Inst", cache1_i_p);

        n_entradas_c5_l.setText("Tamaño:");

        n_entradas_c5_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c5_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c5_t.setName(""); // NOI18N
        n_entradas_c5_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c5_tActionPerformed(evt);
            }
        });

        n_vias_c5_l.setText("Número de vías:");

        n_vias_c5_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c5_l.setText("Política de reemplazo:");

        politica_reemplazo_c5_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c5_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd5ActionPerformed(evt);
            }
        });

        n_tipo_c5_l.setText("Tipo:");

        cb_tipo_cd5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd5.setToolTipText("Tipo de caché.");
        cb_tipo_cd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache2_i_pLayout = new javax.swing.GroupLayout(cache2_i_p);
        cache2_i_p.setLayout(cache2_i_pLayout);
        cache2_i_pLayout.setHorizontalGroup(
            cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c5_l)
                    .addComponent(n_entradas_c5_l)
                    .addComponent(n_tipo_c5_l))
                .addGap(24, 24, 24)
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c5_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c5_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache2_i_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c5_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c5_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache2_i_pLayout.setVerticalGroup(
            cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache2_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c5_l)
                    .addComponent(n_entradas_c5_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c5_l)
                    .addComponent(n_vias_c5_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c5_l)
                    .addComponent(cb_tipo_cd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache2_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c5_l)
                    .addComponent(politica_reemplazo_c5_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 2 Inst", cache2_i_p);

        n_entradas_c6_l.setText("Tamaño:");

        n_entradas_c6_t.setToolTipText("Tamaño de la caché.");
        n_entradas_c6_t.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        n_entradas_c6_t.setName(""); // NOI18N
        n_entradas_c6_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_entradas_c6_tActionPerformed(evt);
            }
        });

        n_vias_c6_l.setText("Número de vías:");

        n_vias_c6_t.setToolTipText("Número de vías para cachés asociativas.");

        politica_reemplazo_c6_l.setText("Política de reemplazo:");

        politica_reemplazo_c6_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LRU", "LFU", "FIFO", "AGING", "RANDOM" }));
        politica_reemplazo_c6_cb.setToolTipText("Política de reemplazo para cachés asociativas.");

        cb_tam_cd6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "KBytes", "MBytes" }));
        cb_tam_cd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tam_cd6ActionPerformed(evt);
            }
        });

        n_tipo_c6_l.setText("Tipo:");

        cb_tipo_cd6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directa", "Asociativa" }));
        cb_tipo_cd6.setToolTipText("Tipo de caché.");
        cb_tipo_cd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipo_cd6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cache3_i_pLayout = new javax.swing.GroupLayout(cache3_i_p);
        cache3_i_p.setLayout(cache3_i_pLayout);
        cache3_i_pLayout.setHorizontalGroup(
            cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(politica_reemplazo_c6_l)
                    .addComponent(n_entradas_c6_l)
                    .addComponent(n_tipo_c6_l))
                .addGap(24, 24, 24)
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipo_cd6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(n_entradas_c6_t, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(politica_reemplazo_c6_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cache3_i_pLayout.createSequentialGroup()
                        .addComponent(n_vias_c6_l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(n_vias_c6_t, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tam_cd6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        cache3_i_pLayout.setVerticalGroup(
            cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cache3_i_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_entradas_c6_l)
                    .addComponent(n_entradas_c6_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tam_cd6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_vias_c6_l)
                    .addComponent(n_vias_c6_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tipo_c6_l)
                    .addComponent(cb_tipo_cd6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cache3_i_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(politica_reemplazo_c6_l)
                    .addComponent(politica_reemplazo_c6_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        cache1_3_p.addTab("Cache 3 Inst", cache3_i_p);

        niv_cache_inst_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        niv_cache_inst_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niv_cache_inst_cbActionPerformed(evt);
            }
        });

        jLabel3.setText("Niveles de Cache Inst:");

        cb_tipo_tam_linea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bytes", "Palabras" }));
        cb_tipo_tam_linea.setToolTipText("");

        javax.swing.GroupLayout caches_pLayout = new javax.swing.GroupLayout(caches_p);
        caches_p.setLayout(caches_pLayout);
        caches_pLayout.setHorizontalGroup(
            caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caches_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caches_pLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(niv_cache_data_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(caches_pLayout.createSequentialGroup()
                        .addComponent(tam_linea_l)
                        .addGap(18, 18, 18)
                        .addComponent(tam_linea_t, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caches_pLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(niv_cache_inst_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_tipo_tam_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(cache1_3_p)
        );
        caches_pLayout.setVerticalGroup(
            caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caches_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(niv_cache_data_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(niv_cache_inst_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(caches_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam_linea_l)
                    .addComponent(tam_linea_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_tam_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cache1_3_p))
        );

        config_p1.addTab("Cache", caches_p);

        javax.swing.GroupLayout ConfiguracionLayout = new javax.swing.GroupLayout(Configuracion);
        Configuracion.setLayout(ConfiguracionLayout);
        ConfiguracionLayout.setHorizontalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(config_p1)
        );
        ConfiguracionLayout.setVerticalGroup(
            ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config_p1))
        );

        config_p1.getAccessibleContext().setAccessibleName("General");

        ejecucion_p.addTab("Configuración", Configuracion);

        ejecucion_a.setEditable(false);
        ejecucion_a.setColumns(20);
        ejecucion_a.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        ejecucion_a.setRows(15);
        ejecucion_a.setTabSize(100);
        jScrollPane1.setViewportView(ejecucion_a);

        ejecutar_b.setText("Ejecutar");

        traza_carga_b.setText("Cargar traza");
        traza_carga_b.setPreferredSize(new java.awt.Dimension(100, 23));
        traza_carga_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traza_carga_bActionPerformed(evt);
            }
        });

        salvar_t.setText("resultado_traza.txt");

        exportar_b.setText("Exportar");

        validar_t_b.setText("Validar");

        limpiar_t_b.setText("Limpiar");

        javax.swing.GroupLayout ejecucionLayout = new javax.swing.GroupLayout(ejecucion);
        ejecucion.setLayout(ejecucionLayout);
        ejecucionLayout.setHorizontalGroup(
            ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(ejecucionLayout.createSequentialGroup()
                        .addComponent(salvar_t)
                        .addGap(18, 18, 18)
                        .addComponent(exportar_b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ejecucionLayout.createSequentialGroup()
                        .addComponent(traza_carga_b, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(validar_t_b)
                        .addGap(18, 18, 18)
                        .addComponent(ejecutar_b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiar_t_b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ejecucionLayout.setVerticalGroup(
            ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traza_carga_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejecutar_b)
                    .addComponent(validar_t_b)
                    .addComponent(limpiar_t_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ejecucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportar_b))
                .addContainerGap())
        );

        ejecucion_p.addTab("Traza", ejecucion);

        ejecucion_a1.setEditable(false);
        ejecucion_a1.setColumns(20);
        ejecucion_a1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        ejecucion_a1.setRows(15);
        ejecucion_a1.setTabSize(100);
        jScrollPane3.setViewportView(ejecucion_a1);

        ejecutar_b1.setText("Ejecutar");

        ciclo_b1.setText("Ciclo");

        salvar_e.setText("resultado_ejecucion.txt");

        exportar_b1.setText("Exportar");

        cargar_codigo_b.setText("Cargar código");
        cargar_codigo_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_codigo_bActionPerformed(evt);
            }
        });

        validar_c_b.setText("Validar");

        cache_d1_b.setText("Cache D1");

        cache_d2_b.setText("Cache D2");

        cache_d3_b.setText("Cache D3");

        cache_i1_b.setText("Cache I1");

        cache_i2_b.setText("Cache I2");

        cache_i3_b.setText("Cache I3");
        cache_i3_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cache_i3_bActionPerformed(evt);
            }
        });

        memoria_b.setText("Memoria");

        limpiar_ej_b.setText("Limpiar");

        javax.swing.GroupLayout ejecucion1Layout = new javax.swing.GroupLayout(ejecucion1);
        ejecucion1.setLayout(ejecucion1Layout);
        ejecucion1Layout.setHorizontalGroup(
            ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(ejecucion1Layout.createSequentialGroup()
                        .addComponent(cargar_codigo_b, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(validar_c_b)
                        .addGap(18, 18, 18)
                        .addComponent(ejecutar_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ciclo_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiar_ej_b, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ejecucion1Layout.createSequentialGroup()
                        .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ejecucion1Layout.createSequentialGroup()
                                .addComponent(salvar_e)
                                .addGap(18, 18, 18))
                            .addGroup(ejecucion1Layout.createSequentialGroup()
                                .addComponent(cache_d1_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cache_d2_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cache_d3_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cache_i1_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cache_i2_b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cache_i3_b)
                                .addGap(13, 13, 13)))
                        .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exportar_b1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(memoria_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ejecucion1Layout.setVerticalGroup(
            ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecucion1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargar_codigo_b)
                    .addComponent(ciclo_b1)
                    .addComponent(ejecutar_b1)
                    .addComponent(validar_c_b)
                    .addComponent(limpiar_ej_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cache_d1_b)
                    .addComponent(cache_d2_b)
                    .addComponent(cache_d3_b)
                    .addComponent(cache_i1_b)
                    .addComponent(cache_i2_b)
                    .addComponent(cache_i3_b)
                    .addComponent(memoria_b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ejecucion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportar_b1))
                .addContainerGap())
        );

        ejecucion_p.addTab("Ejecución", ejecucion1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ejecucion_p, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ejecucion_p)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tlb_data_chbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlb_data_chbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlb_data_chbActionPerformed

    private void traza_carga_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traza_carga_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traza_carga_bActionPerformed

    private void niv_cache_inst_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niv_cache_inst_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niv_cache_inst_cbActionPerformed

    private void niv_cache_data_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niv_cache_data_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niv_cache_data_cbActionPerformed

    private void cb_tam_paginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_paginaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_paginaActionPerformed

    private void cb_tam_mempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_mempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_mempActionPerformed

    private void cb_tam_virtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_virtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_virtActionPerformed

    private void cargar_codigo_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_codigo_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargar_codigo_bActionPerformed

    private void cb_tam_cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd1ActionPerformed

    private void cb_tipo_tlb_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_tlb_datosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_tlb_datosActionPerformed

    private void cb_tipo_tlb_instActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_tlb_instActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_tlb_instActionPerformed

    private void cb_tipo_cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd1ActionPerformed

    private void n_entradas_c1_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c1_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c1_tActionPerformed

    private void n_entradas_tlb_inst_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_tlb_inst_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_tlb_inst_tActionPerformed

    private void cb_tipo_cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd2ActionPerformed

    private void cb_tam_cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd2ActionPerformed

    private void n_entradas_c2_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c2_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c2_tActionPerformed

    private void n_entradas_c3_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c3_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c3_tActionPerformed

    private void cb_tam_cd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd3ActionPerformed

    private void cb_tipo_cd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd3ActionPerformed

    private void n_entradas_c4_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c4_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c4_tActionPerformed

    private void cb_tam_cd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd4ActionPerformed

    private void cb_tipo_cd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd4ActionPerformed

    private void n_entradas_c5_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c5_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c5_tActionPerformed

    private void cb_tam_cd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd5ActionPerformed

    private void cb_tipo_cd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd5ActionPerformed

    private void n_entradas_c6_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_entradas_c6_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_entradas_c6_tActionPerformed

    private void cb_tam_cd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tam_cd6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tam_cd6ActionPerformed

    private void cb_tipo_cd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipo_cd6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipo_cd6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Configuracion;
    private javax.swing.JTabbedPane cache1_3_p;
    private javax.swing.JPanel cache1_i_p;
    private javax.swing.JPanel cache1_p;
    private javax.swing.JPanel cache2_i_p;
    private javax.swing.JPanel cache2_p;
    private javax.swing.JPanel cache3_i_p;
    private javax.swing.JPanel cache3_p;
    private javax.swing.JButton cache_d1_b;
    private javax.swing.JButton cache_d2_b;
    private javax.swing.JButton cache_d3_b;
    private javax.swing.JButton cache_i1_b;
    private javax.swing.JButton cache_i2_b;
    private javax.swing.JButton cache_i3_b;
    private javax.swing.JPanel caches_p;
    private javax.swing.JComboBox caches_separadas_cb;
    private javax.swing.JButton cargar_codigo_b;
    private javax.swing.JComboBox cb_tam_cd1;
    private javax.swing.JComboBox cb_tam_cd2;
    private javax.swing.JComboBox cb_tam_cd3;
    private javax.swing.JComboBox cb_tam_cd4;
    private javax.swing.JComboBox cb_tam_cd5;
    private javax.swing.JComboBox cb_tam_cd6;
    private javax.swing.JComboBox cb_tam_memp;
    private javax.swing.JComboBox cb_tam_pagina;
    private javax.swing.JComboBox cb_tam_virt;
    private javax.swing.JComboBox cb_tipo_cd1;
    private javax.swing.JComboBox cb_tipo_cd2;
    private javax.swing.JComboBox cb_tipo_cd3;
    private javax.swing.JComboBox cb_tipo_cd4;
    private javax.swing.JComboBox cb_tipo_cd5;
    private javax.swing.JComboBox cb_tipo_cd6;
    private javax.swing.JComboBox cb_tipo_tam_linea;
    private javax.swing.JComboBox cb_tipo_tlb_datos;
    private javax.swing.JComboBox cb_tipo_tlb_inst;
    private javax.swing.JButton ciclo_b1;
    private javax.swing.JTabbedPane config_p1;
    private javax.swing.JPanel cpu_p;
    private javax.swing.JPanel ejecucion;
    private javax.swing.JPanel ejecucion1;
    private javax.swing.JTextArea ejecucion_a;
    private javax.swing.JTextArea ejecucion_a1;
    private javax.swing.JTabbedPane ejecucion_p;
    private javax.swing.JButton ejecutar_b;
    private javax.swing.JButton ejecutar_b1;
    private javax.swing.JButton exportar_b;
    private javax.swing.JButton exportar_b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jerarquias_separadas_l;
    private javax.swing.JButton limpiar_ej_b;
    private javax.swing.JButton limpiar_t_b;
    private javax.swing.JComboBox log_cb;
    private javax.swing.JLabel m_entradas_p_pagina_l;
    private javax.swing.JTextField m_entradas_p_pagina_t;
    private javax.swing.JLabel m_numero_entradas;
    private javax.swing.JTextField m_tam_memp_t;
    private javax.swing.JTextField m_tam_virt_t;
    private javax.swing.JButton memoria_b;
    private javax.swing.JPanel memoria_p;
    private javax.swing.JLabel n_entradas_c1_l;
    private javax.swing.JTextField n_entradas_c1_t;
    private javax.swing.JLabel n_entradas_c2_l;
    private javax.swing.JLabel n_entradas_c2_l4;
    private javax.swing.JLabel n_entradas_c2_l6;
    private javax.swing.JLabel n_entradas_c2_l7;
    private javax.swing.JLabel n_entradas_c2_l8;
    private javax.swing.JTextField n_entradas_c2_t;
    private javax.swing.JLabel n_entradas_c3_l;
    private javax.swing.JTextField n_entradas_c3_t;
    private javax.swing.JLabel n_entradas_c4_l;
    private javax.swing.JTextField n_entradas_c4_t;
    private javax.swing.JLabel n_entradas_c5_l;
    private javax.swing.JTextField n_entradas_c5_t;
    private javax.swing.JLabel n_entradas_c6_l;
    private javax.swing.JTextField n_entradas_c6_t;
    private javax.swing.JTextField n_entradas_tlb_data_t;
    private javax.swing.JTextField n_entradas_tlb_inst_t;
    private javax.swing.JLabel n_tipo_c1_l;
    private javax.swing.JLabel n_tipo_c2_l;
    private javax.swing.JLabel n_tipo_c3_l;
    private javax.swing.JLabel n_tipo_c4_l;
    private javax.swing.JLabel n_tipo_c5_l;
    private javax.swing.JLabel n_tipo_c6_l;
    private javax.swing.JLabel n_vias_c1_l;
    private javax.swing.JTextField n_vias_c1_t;
    private javax.swing.JLabel n_vias_c2_l;
    private javax.swing.JLabel n_vias_c2_l4;
    private javax.swing.JLabel n_vias_c2_l6;
    private javax.swing.JTextField n_vias_c2_t;
    private javax.swing.JLabel n_vias_c3_l;
    private javax.swing.JTextField n_vias_c3_t;
    private javax.swing.JLabel n_vias_c4_l;
    private javax.swing.JTextField n_vias_c4_t;
    private javax.swing.JLabel n_vias_c5_l;
    private javax.swing.JTextField n_vias_c5_t;
    private javax.swing.JLabel n_vias_c6_l;
    private javax.swing.JTextField n_vias_c6_t;
    private javax.swing.JTextField n_vias_tlb_data_t;
    private javax.swing.JTextField n_vias_tlb_inst_t;
    private javax.swing.JComboBox niv_cache_data_cb;
    private javax.swing.JComboBox niv_cache_inst_cb;
    private javax.swing.JLabel pal_p_linea_l;
    private javax.swing.JTextField pal_p_linea_t;
    private javax.swing.JComboBox politica_reemplazo_c1_cb;
    private javax.swing.JLabel politica_reemplazo_c1_l;
    private javax.swing.JLabel politica_reemplazo_c1_l1;
    private javax.swing.JLabel politica_reemplazo_c1_l3;
    private javax.swing.JComboBox politica_reemplazo_c2_cb;
    private javax.swing.JLabel politica_reemplazo_c2_l;
    private javax.swing.JComboBox politica_reemplazo_c3_cb;
    private javax.swing.JLabel politica_reemplazo_c3_l;
    private javax.swing.JComboBox politica_reemplazo_c4_cb;
    private javax.swing.JLabel politica_reemplazo_c4_l;
    private javax.swing.JComboBox politica_reemplazo_c5_cb;
    private javax.swing.JLabel politica_reemplazo_c5_l;
    private javax.swing.JComboBox politica_reemplazo_c6_cb;
    private javax.swing.JLabel politica_reemplazo_c6_l;
    private javax.swing.JComboBox politica_reemplazo_tlb_data_cb1;
    private javax.swing.JComboBox politica_reemplazo_tlb_inst_cb;
    private javax.swing.JTextField salvar_e;
    private javax.swing.JTextField salvar_t;
    private javax.swing.JLabel tam_linea_l;
    private javax.swing.JTextField tam_linea_t;
    private javax.swing.JCheckBox tlb_data_chb;
    private javax.swing.JCheckBox tlb_inst_chb;
    private javax.swing.JButton traza_carga_b;
    private javax.swing.JButton validar_c_b;
    private javax.swing.JButton validar_t_b;
    // End of variables declaration//GEN-END:variables
    
    public void controlador(ActionListener ctr)
    {
    	niv_cache_data_cb.setActionCommand(Global.CBNCACHE);
    	niv_cache_data_cb.addActionListener(ctr);
    	tlb_data_chb.setActionCommand(Global.TLBDATA);
    	tlb_data_chb.addActionListener(ctr);
    	jerarquias_separadas_chb.setActionCommand(Global.JSEP);
    	jerarquias_separadas_chb.addActionListener(ctr);
    	niv_cache_inst_cb.setActionCommand(Global.CBNCACHEI);
    	niv_cache_inst_cb.addActionListener(ctr);
    	tlb_inst_chb.setActionCommand(Global.TLBINST);
    	tlb_inst_chb.addActionListener(ctr);
    	cargar_codigo_b.setActionCommand(Global.CARGARC);
    	cargar_codigo_b.addActionListener(ctr);
    	//sin añadir al controlador
    	traza_carga_b.setActionCommand(Global.CARGART);
    	traza_carga_b.addActionListener(ctr);
    	validar_c_b.setActionCommand(Global.VALC);
    	validar_c_b.addActionListener(ctr);
    	validar_t_b.setActionCommand(Global.VALT);
    	validar_t_b.addActionListener(ctr);
    	cache_d1_b.setActionCommand(Global.BCACHED1);
    	cache_d1_b.addActionListener(ctr);
    	cache_d2_b.setActionCommand(Global.BCACHED2);
    	cache_d2_b.addActionListener(ctr);
    	cache_d3_b.setActionCommand(Global.BCACHED3);
    	cache_d3_b.addActionListener(ctr);
    	cache_i1_b.setActionCommand(Global.BCACHEI1);
    	cache_i1_b.addActionListener(ctr);
    	cache_i2_b.setActionCommand(Global.BCACHEI2);
    	cache_i2_b.addActionListener(ctr);
    	cache_i3_b.setActionCommand(Global.BCACHEI3);
    	cache_i3_b.addActionListener(ctr);
    	memoria_b.setActionCommand(Global.BMEM);
    	memoria_b.addActionListener(ctr);
    	ejecutar_b.setActionCommand(Global.EJECUTART);
    	ejecutar_b.addActionListener(ctr);
    	ejecutar_b1.setActionCommand(Global.EJECUTARC);
    	ejecutar_b1.addActionListener(ctr);
    	ciclo_b1.setActionCommand(Global.CICLO);
    	ciclo_b1.addActionListener(ctr);
    	
    }
    public int getnvCache()
    {
    	return Integer.parseInt(niv_cache_data_cb.getSelectedItem().toString());
    }
    public int getnvCacheI()
    {
    	return Integer.parseInt(niv_cache_inst_cb.getSelectedItem().toString());
    }
    public boolean tlbDataCheck()
    {
    	boolean b;
    	if(tlb_data_chb.isSelected())
    	{
    		b=true;
    	}
    	else
    	{
    		b=false;
    	}
    	return b;
    }
    public boolean tlbInstCheck()
    {
    	boolean b;
    	if(tlb_inst_chb.isSelected())
    	{
    		b=true;
    	}
    	else
    	{
    		b=false;
    	}
    	return b;
    }
    public boolean jsepCheck()
    {
    	boolean b;
    	if(jerarquias_separadas_chb.isSelected())
    	{
    		b=true;
    	}
    	else
    	{
    		b=false;
    	}
    	return b;
    }
    public void nvCacheData(int n)
    {
    	if(n==1)
    	{
    		cache1_3_p.setEnabledAt(1, false);
    		cache1_3_p.setEnabledAt(2, false);
    		cache_d2_b.setEnabled(false);
            cache_d3_b.setEnabled(false);

    	}
    	else if(n==2)
    	{
    		cache1_3_p.setEnabledAt(1, true);
    		cache1_3_p.setEnabledAt(2, false);
    		cache_d2_b.setEnabled(true);
            cache_d3_b.setEnabled(false);
 

    	}
    	else if (n==3)
    	{
    		cache1_3_p.setEnabledAt(1, true);
    		cache1_3_p.setEnabledAt(2, true);
    		cache_d2_b.setEnabled(true);
            cache_d3_b.setEnabled(true);

    	}
    	cache1_3_p.setSelectedIndex(getnvCache()-1);
    }
    public void nvCacheInst(int n)
    {
    	if(n==1)
    	{
    		cache1_3_p.setEnabledAt(4, false);
    		cache1_3_p.setEnabledAt(5, false);
    		cache_i2_b.setEnabled(false);
            cache_i3_b.setEnabled(false);
    		
    	}
    	else if(n==2)
    	{
    		cache1_3_p.setEnabledAt(4, true);
    		cache1_3_p.setEnabledAt(5, false);
    		cache_i2_b.setEnabled(true);
            cache_i3_b.setEnabled(false);
    	

    	}
    	else if (n==3)
    	{
    		cache1_3_p.setEnabledAt(4, true);
    		cache1_3_p.setEnabledAt(5, true);
    		cache_i2_b.setEnabled(true);
            cache_i3_b.setEnabled(true);
 
    	}
    	cache1_3_p.setSelectedIndex(getnvCacheI()+2);
    }
    public void enabledJSEP(boolean b)
    {
    	niv_cache_inst_cb.setEnabled(b);
        tlb_inst_chb.setEnabled(b);
        
        if(!b)
        {
        	cache1_3_p.setEnabledAt(3, b);
        	cache1_3_p.setEnabledAt(4, b);
    		cache1_3_p.setEnabledAt(5, b);
    		cache1_3_p.setSelectedIndex(0);
    		cache_i1_b.setEnabled(b);
    		cache_i2_b.setEnabled(b);
    		cache_i3_b.setEnabled(b);
    		niv_cache_inst_cb.setSelectedIndex(0);
    		enabledTLBInst(b);
        }
        else
        {
        	cache1_3_p.setEnabledAt(3, b);
        	niv_cache_inst_cb.setSelectedIndex(0);
        	cache1_3_p.setEnabledAt(4, !b);
    		cache1_3_p.setEnabledAt(5, !b);
    		cache_i1_b.setEnabled(b);
    		
        }
        
    }
    public void enabledTLBInst(boolean b)
    {
    	jTabbedPane1.setEnabledAt(1, b);
    	if(b)
    	{
    		jTabbedPane1.setSelectedIndex(1);
    	}
    	else
    	{
    		jTabbedPane1.setSelectedIndex(0);
    	}
    	
    }
    public void enabledTLBData(boolean b)
    {
    	n_entradas_tlb_data_t.setEnabled(b);
    	n_vias_tlb_data_t.setEnabled(b);
    	politica_reemplazo_tlb_data_cb1.setEnabled(b);
    }
    public void enabledValidarT()
    {
    	validar_t_b.setEnabled(true);
    }
    public void enabledEjecutarT()
    {
    	ejecutar_b.setEnabled(true);
    }
    public void enabledValidarC()
    {
    	validar_c_b.setEnabled(true);
    }
    public void enabledEjecutarC()
    {
    	ejecutar_b1.setEnabled(true);
    	ciclo_b1.setEnabled(true);
    }
    public int getTamPal()
    {
    	return Integer.decode(pal_p_linea_t.getText());
    }
    public int getSegmentado()
    {
    	if(segmentado_chb.isSelected())
    	{
    		return 1;
    	}
    	else
    	{
    	return 0;
    	}
    }
    public int getEntradasPagina()
    {
    	return Integer.decode(m_entradas_p_pagina_t.getText());
    }
    public int getNumEntradasMem()
    {
    	return Integer.decode(m_tam_memp_t.getText());
    }
    public int getMaxNumEntradas()
    {
    	return Integer.decode(m_max_ent_mem_t.getText());
    }
    public int getTLBDNumEntradas()
    {
    	return Integer.decode(n_entradas_tlb_data_t.getText());
    }
    public int getTLBDNumVias()
    {
    	return Integer.decode(n_vias_tlb_data_t.getText());
    }
    public String getPRTLBD()
    {
    	return politica_reemplazo_tlb_data_cb1.getSelectedItem().toString();
    }
    public int getTLBINumEntradas()
    {
    	return Integer.decode(n_entradas_tlb_ins_t.getText());
    }
    public int getTLBINumVias()
    {
    	return Integer.decode(n_vias_tlb_ins_t.getText());
    }
    public String getPRTLBI()
    {
    	return politica_reemplazo_tlb_ins_cb.getSelectedItem().toString();
    }
    public String getTipTamCache()
    {
    	return tip_tam_cache1_cb.getSelectedItem().toString();
    }
    public int getTamLinea()
    {
    	return Integer.decode(tam_linea_t.getText());
    }
    public int getCD1NEntradas()
    {
    	return Integer.decode(n_entradas_c1_t.getText());
    }
    public int getCD2NEntradas()
    {
    	return Integer.decode(n_entradas_c2_t.getText());
    }
    public int getCD3NEntradas()
    {
    	return Integer.decode(n_entradas_c3_t.getText());
    }
    public int getCI1NEntradas()
    {
    	return Integer.decode(n_entradas_c1_i_t.getText());
    }
    public int getCI2NEntradas()
    {
    	return Integer.decode(n_entradas_c2_i_t.getText());
    }
    public int getCI3NEntradas()
    {
    	return Integer.decode( n_entradas_c3_i_t.getText());
    }
    public int getCD1NVias()
    {
    	return Integer.decode(n_vias_c1_t.getText());
    }
    public int getCD2NVias()
    {
    	return Integer.decode(n_vias_c2_t.getText());
    }
    public int getCD3NVias()
    {
    	return Integer.decode(n_vias_c3_t.getText());
    }
    public int getCI1NVias()
    {
    	return Integer.decode(n_vias_c1_i_t.getText());
    }
    public int getCI2NVias()
    {
    	return Integer.decode(n_vias_c2_i_t.getText());
    }
    public int getCI3NVias()
    {
    	return Integer.decode(n_vias_c3_i_t.getText());
    }
    public String getPRCD1()
    {
    	return politica_reemplazo_c1_cb.getSelectedItem().toString();
    }
    public String getPRCD2()
    {
    	return politica_reemplazo_c2_cb.getSelectedItem().toString();
    }
    public String getPRCD3()
    {
    	return politica_reemplazo_c3_cb.getSelectedItem().toString();
    }
    public String getPRCI1()
    {
    	return politica_reemplazo_c1_i_cb.getSelectedItem().toString();
    }
    public String getPRCI2()
    {
    	return politica_reemplazo_c2_i_cb.getSelectedItem().toString();
    }
    public String getPRCI3()
    {
    	return politica_reemplazo_c3_i_cb.getSelectedItem().toString();
    }
    public void resTraza(String t)
    {
    	ejecucion_a.append(t);
    }
    public void resEjec(String t)
    {
    	ejecucion_a1.append(t);
    }
    public void enabledConfig(boolean b)
    {
    	ejecucion_p.setEnabledAt(0, b);
    }
    public void resetTraza()
    {
    	ejecucion_a.setText("");
    }
    public void resetEjec()
    {
    	ejecucion_a1.setText("");
    }
    public String getTraza()
    {
    	return ejecucion_a.getText();
    }
    public String getEjec()
    {
    	return ejecucion_a1.getText();
    }
}
